### PR TITLE
added-description - added description to interaction builder

### PR DESCRIPTION
**Pull request by suryaiscrazy**
Added description to interaction builder so that contracts can be created with not null description

### CODE REVIEW

**Comment by reevoo-samuel** [comment]
Er, hello?

This Pull Request is too damn old! Merge or close this, sucka.

**Comment by reevoo-samuel** [comment]
Er, hello?

This Pull Request is too damn old! Merge or close this, sucka.

**Comment by reevoo-samuel** [comment]
Er, hello?

This Pull Request is too damn old! Merge or close this, sucka.

**Comment by reevoo-samuel** [comment]
Er, hello?

This Pull Request is too damn old! Merge or close this, sucka.

**Comment by reevoo-samuel** [comment]
Er, hello?

This Pull Request is too damn old! Merge or close this, sucka.

**Review by amalkov — APPROVED** [review]

**Review by amalkov — CHANGES_REQUESTED** [review]
Please fix your tests

**Comment by suryaiscrazy** [comment]
All set

**Comment by reevoo-samuel** [comment]
Er, hello?

This Pull Request is too damn old! Merge or close this, sucka.

**Comment by reevoo-samuel** [comment]
Er, hello?

This Pull Request is too damn old! Merge or close this, sucka.

**Comment by reevoo-samuel** [comment]
Er, hello?

This Pull Request is too damn old! Merge or close this, sucka.

**Comment by reevoo-samuel** [comment]
Er, hello?

This Pull Request is too damn old! Merge or close this, sucka.

**Review by amalkov — APPROVED** [review]

**Comment by suryaiscrazy** [comment]
Thanks Alex. Can you release the new version for us too, -v 0.1.2

**Pull request merged**
